name = "zkkb-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "zkkb"
database_id = "01470a31-1ece-4637-bab5-fdad8650f6bb"

# R2 Bucket
[[r2_buckets]]
binding = "R2"
bucket_name = "zkkb"

# Durable Objects
[[durable_objects.bindings]]
name = "BOARD_SYNC"
class_name = "BoardSync"

[[migrations]]
tag = "v1"
new_classes = ["BoardSync"]
